### ISSUE TITLE
Deleting components (specifically cbench scoreboard) from cKnowledge.io?

### ISSUE THREAD

**Issue by phesse001** [ctuning/ck#127]
Is there a way to delete a graph from cknowledge.io? In the initial phases of creating a graph, when you are deciding on how you would like it to be formatted, it can be useful to push some test points to the plot, and if they are in the wrong format or you were simply using them for testing, it would be nice to be able to remove them for testing purposes. Maybe add a --permanent flag for when graph is stable and ready to accept points pushed of the proper format?

**Comment by gfursin** [comment]
Hi @phesse001.

Thank you for your feedback - it is very timely!

cKnowledge.io scoreboards and solutions is a very preliminary and proof-of-concept functionality, and I plan to start improving it soon.

My idea is to let researchers create such scoreboards for their submitted papers, and then provide a "solution" to make it easier for artifact evaluators to reproduce results and push them to the same scoreboard. If there is a discrepancy, it will be reported to let researchers work together to solve problems.

However, at the moment, it's impossible to delete components from cKnowledge.io - my original idea was to make it a bit like Zenodo or other permanent archives so that we could always trace what was created by users (with CK Unique IDs). However, I already see that this is not that good for test cases like yours. That's why I should probably add a possibility to delete a graph if you are an owner, and then use a "--permanent" flag to mark it as stable and permanent (for example, after artifact evaluation). 

I will think about it and will get back to you when I have a solution ...

**Comment by gfursin** [comment]
Hi @phesse001.

I added the functionality to delete components from the CK portal (for owner and if not permanent), and it is also possible to publish components and mark them as permanent with flag `cb publish --permanent ...`.

I also fixed the problem with the graph, i.e. the platform should now ignore results in the wrong format.

May I ask you to check it, please?

You need to update cbench to v1.3.1 (I just uploaded it to Pypi):
```
pip install cbench -U
```

You can then try to delete your graph as follows:
```
cb delete result:march-madness-results
```

Please don't forget to send a note to the CK mailing list to et CK users know about your tests - it can be useful for them too!

Thanks a lot and tell me if you encounter other issues!

**Comment by phesse001** [comment]
Hey @gfursin 

I tested the functionality and all seems to be working from my end!

I ended up pushing some different graphs because the 'result:march-madness-results' one was marked as permanent already, so you might have to forcefully remove that one if you can but I can now create graphs and delete non-permanent ones just as easily.

Pushing an invalid point also no longer breaks the graph based on a couple test points I pushed.

One note on the docs I noticed: the cBench docs mentions you can push a result with the following:

`cb push-result {name of the existing dashboard} --file="$PWD/result.json"`

but the key it accepts is --filename

Everything seems to be working well - Again, thanks for adding this feature, it will be useful for trying out different graph/table formats.

I'll throw a note in the mailing list later today when I get the chance

**Comment by gfursin** [comment]
Cool! Thanks @phesse001!

Oh, I added "permanent" key to your dashboard just for testing and then forgot to remove it ;) ... I just removed it so you should be able to delete it if you need so.

Also thanks a lot for spotting the mistake in the documentation - I fixed that!

I am closing this ticket and if you have any further questions, issues or feedback, please keep in touch!
