### ISSUE TITLE
ck install package --tags=lib,tflite,v1.13 fails

### ISSUE THREAD

**Issue by tom-gall** [ctuning/ck#138]
This little snippet captures what is going on :
  git checkout -b <new-branch-name>

HEAD is now at 6612da89516 Merge pull request #26101 from gunan/r1.13
--------------------------------
Preparing sources ...

[Patcher] Patching of the original code enabled
[Patcher] Original patch patterns: ${ORIGINAL_PACKAGE_DIR}/patch.${CK_TARGET_OS_ID}/*
[Patcher] Resolved patch filenames: /home/debian/CK/ck-tensorflow/package/lib-tflite-1.13.1-src-static/patch.linux/Makefile.patch
[Patcher] Applying patch /home/debian/CK/ck-tensorflow/package/lib-tflite-1.13.1-src-static/patch.linux/Makefile.patch
patching file tensorflow/lite/tools/make/Makefile
--------------------------------
Download dependencies ...

downloading https://bitbucket.org/eigen/eigen/get/9f48e814419e.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

futher

$ wget https://bitbucket.org/eigen/eigen/get/9f48e814419e.tar.gz
--2021-04-02 14:55:11--  https://bitbucket.org/eigen/eigen/get/9f48e814419e.tar.gz
Resolving bitbucket.org (bitbucket.org)... 104.192.141.1, 2406:da00:ff00::22c2:513, 2406:da00:ff00::22cd:e0db, ...
Connecting to bitbucket.org (bitbucket.org)|104.192.141.1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-04-02 14:55:12 ERROR 404: Not Found.

**Comment by gfursin** [comment]
Hi @tom-gall . Thank you very much for reporting!

The problem is that eigen was moved from bitbucket to gitlab. I found a solution [here](https://github.com/tensorflow/tensorflow/issues/43348) and added "eigen.patch" to CK tflite packages v1.13,1.14 and 1.15 (see it in "files section" at [cKnowledge.io](https://cknowledge.io/c/package/lib-tflite-1.15.0-src-static/)):

* https://github.com/ctuning/ck-mlperf/tree/master/package/lib-tflite-1.15.0-rc2-src-static
* https://github.com/ctuning/ck-tensorflow/tree/master/package/lib-tflite-1.13.1-src-static
* https://github.com/ctuning/ck-tensorflow/tree/master/package/lib-tflite-1.14.0-src-static
* https://github.com/ctuning/ck-tensorflow/tree/master/package/lib-tflite-1.15.0-src-static

Please, update your CK repos as follows and try again:
```
ck pull all
ck install package --tags=lib,tflite,v1.13
```

Hope it works! Thanks again for reporting!

**Comment by tom-gall** [comment]
This is back in a good state, thank you!

**Comment by gfursin** [comment]
Great! Thanks @tom-gall for the feedback! Glad that it worked!

By the way, just a note that I've moved further CK ML developments to the ck-ml repository - it aggregates all stable CK components from the community for AI/ML in one place to make it easier to test and use them ...

Cheers!
