### ISSUE TITLE
ck install package --tags=lib,tflite,v1.15 fails

### ISSUE THREAD

**Issue by tom-gall** [ctuning/ck#139]
Same problem as the issue with trying to install tflite v1.13

Download dependencies ...

downloading https://bitbucket.org/eigen/eigen/get/49177915a14a.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

wget  https://bitbucket.org/eigen/eigen/get/49177915a14a.tar.gz
--2021-04-02 15:06:59--  https://bitbucket.org/eigen/eigen/get/49177915a14a.tar.gz
Resolving bitbucket.org (bitbucket.org)... 104.192.141.1, 2406:da00:ff00::6b17:d1f5, 2406:da00:ff00::22c2:513, ...
Connecting to bitbucket.org (bitbucket.org)|104.192.141.1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-04-02 15:06:59 ERROR 404: Not Found.

**Comment by gfursin** [comment]
Hi @tom-gall . Thank you very much for reporting!

The problem is that eigen was moved from bitbucket to gitlab. I found a solution [here](https://github.com/tensorflow/tensorflow/issues/43348) and added "eigen.patch" to CK tflite packages v1.13,1.14 and 1.15 (see it in "files section" at [cKnowledge.io](https://cknowledge.io/c/package/lib-tflite-1.15.0-src-static/)):

* https://github.com/ctuning/ck-mlperf/tree/master/package/lib-tflite-1.15.0-rc2-src-static
* https://github.com/ctuning/ck-tensorflow/tree/master/package/lib-tflite-1.13.1-src-static
* https://github.com/ctuning/ck-tensorflow/tree/master/package/lib-tflite-1.14.0-src-static
* https://github.com/ctuning/ck-tensorflow/tree/master/package/lib-tflite-1.15.0-src-static

Please, update your CK repos as follows and try again:
```
ck pull all
ck install package --tags=lib,tflite,v1.15
```

Hope it works! Thanks again for reporting!

**Comment by filven** [comment]
I had to wget manually the eigen file, the ck pull all wouldn't fetch it.

**Comment by gfursin** [comment]
Hi @tom-gall . 
I have to admit that I didn't check the KRAI's fork. 
I have been fixing the packages in the official MLCommons repository:  
* https://github.com/mlcommons/ck-mlops .
* https://github.com/mlcommons/ck-mlops/blob/main/package/lib-tflite-1.13.1-src-static/patch.linux/eigen.patch
Normally, you should be able to install the new CK framework (2.5.7), then pull the above repository and then run MLPerf TFLite workflows:
```
python3 -m pip install ck
ck pull repo:mlcommons@ck-mlops
...
```

By the way, I had a discussion with KRAI's colleagues to merge their updates to the official MLCommons repository and there is an interest to do so - we just need to find time ;) ...

Thanks!
