### ISSUE TITLE
simple decision tree example

### ISSUE THREAD

**Issue by syakush** [ctuning/ck#31]
please provide basic example for machine learning / decision trees.
input: csv file with values of features and labels (boolean)
  program_size, opt_flag, is_cmov_expected
                    20, O2        , no
                    20, O3        , yes
                    20, Os        , yes
output: dot file with decision tree

**Comment by gfursin** [comment]
Sergey, I created a simple demo for your example:
You can get it here:
$ ck pull repo:ck-analytics
$ ck find demo:ml-decision-tree

In this directory you have two scripts:
$ ./model-sklearn-dtc-build.bat
$ ./model-sklearn-dtc-validate.bat

Input is in model-input.json

It will create a model and will produce various useful files including .dot, .pdf, .png, etc ...:
model-sklearn-dtc.model.*

Can you please check it and if it's ok close this ticket ...
Thanks a lot!

**Comment by gfursin** [comment]
Note that categorical feature dimensions are currently converted into floats (since I didn't find universal way in our ML modules to support strings directly), so you will see such conversion when building a decision tree. Alternatively, we can convert such string to floats before using CK ML (to keep consistency) ...

By the way, I also added CK mode to record produced predictive models (with all extra useful information) in a CK entry and to reuse it, i.e. just give some features and get answer. 

Finally, I added small demo description here: https://github.com/ctuning/ck/wiki/Getting_started_guide_basic_ml
