### ISSUE TITLE
New coverage tests fail 2 times on Windows

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck#63]
Hi Dmitry,
I ran new coverage tests on my Windows machine and got the following 2 errors. Do you mind to check them, please?
Thanks!

[error.txt](https://github.com/ctuning/ck/files/489652/error.txt)

**Comment by gfursin** [comment]
By the way, what is interesting, that Appveyor didn't detect a problem on Windows ...

**Comment by dsavenko** [comment]
Appveyor didn't detect it, because even if some tests failed, `ck run test` returns `0` retcode. I'm fixing this now, along with the failing tests. Will provide PR shortly.

**Comment by dsavenko** [comment]
The tests failing because I forget about path separator again. Should we make so, that function `list_all_files` return filenames with `/` as separator, even if it runs on windows? And, at a larger scope, that kernel always return any path strings with `/` separator, regardless of the actual platform path separator? This would simplify coding.

**Comment by gfursin** [comment]
I would not do it at this stage. The thing is that we use paths prepared in CK in some Windows  batch scripts (package install for example) - we will start mixing / and \ then and may encounter unexpected behaviour across different Windows version. So I would prefer not to do it. Alternatively, later we may create list_all_files2 and gradually deprecate original one.

**Comment by gfursin** [comment]
Tests now passed fine on my Windows 10 machine. Thanks!
