### ISSUE TITLE
Provide an API to find the full path to CK

### ISSUE THREAD

**Issue by dsavenko** [ctuning/ck#72]
Hi,

CK kernel lacks API to get the full path to CK binary. This is needed mostly for writing scripts, so that they don't rely on the PATH environment variable. Relying on PATH is error-prone in various situations. So, we probably need to add such an API (a kernel call or something, the exact form is discussable).

**Comment by gfursin** [comment]
I am updating CK and checked various possibilities to get full path to CK binary. In fact, I know why I don't have it - because in many cases it's impossible. The thing is that CK can be called directly from Python modules, or from command line as python module (python -m) or via ck/ck.bat. But the last one can be spread in different directories depending on installation (python vs Anaconda distro on Linux and Windows). So we can not have such API. Furthermore, as I mentioned, we should not hardwire path to CK in other scripts and that's why we still rely on PATH. I don't see other ways of doing it at the moment. Since we fixed this problem in DNN desktop app, I close this ticket. If someone will really needs it and have an idea how to address above issues I mentioned, we will re-open this ticket again.
