### ISSUE TITLE
Provide a decent documentation

### ISSUE THREAD

**Issue by Sckholar** [ctuning/ck#94]
The current documentation in the Wiki is incomplete and mainly example-based. At least I was unable to find any information on the full API and or JSON content of meta.json in the various places. Even more simple: CK uses 'module', 'package', 'soft', 'program' and a plethora of others without a clear overview or definition what they are and how they related to each other.

Even the existing examples show mainly how to use existing repositories, not how to create a new one. How, for example, to achieve the rather common task of fetching a source repo and compiling the contained code via its Makefile? No indication whatsoever in the wiki :-/

Since I like the overall idea of the project, I'd really appreciate a proper documentation.

**Comment by gfursin** [comment]
Thank you for your feedback, @Sckholar!

As you correctly noticed, current CK documentation is mainly example-based. Since most of our users were not actively contributing to CK until recently or were doing so with our help, they actually asked us to have an example-based documentation ;) ! 

Also, from our experience, it seems to be the only way to design a very large, distributed and evolving system with very limited resources and under continuous updates by the community! CK just provides a way for users to share their code and data (such as 'module', 'package', 'soft', 'program' and many others) with a common API, and connect them together via CK kernel functions. Users then find the most similar “components” and create their own ones based on examples. If such examples are not found, users usually ask other CK users via CK Slack or CK google group:
* https://groups.google.com/forum/#!forum/collective-knowledge
* https://collective-knowledge.slack.com/
The Slack channel is active and we helped many partners to share or improve their CK components – please consider joining it!

We also keep an index of some shared modules and their APIs here: 
* http://cKnowledge.org/shared-modules.html
* http://cKnowledge.org/ck-kernel-functions.html

However, we now see that some modules and workflows are becoming stable including the ones you mentioned! In such case, I totally agree with you that it’s better to have a proper documentation – in fact, we already started discussing with our users how to document stable components and workflows to simplify life of CK contributors ;) !  

We hope to find some resources to improve documentation of those components in Q1 2019 and will consider your feedback! In the meantime, as a non-profit community project, we rely mainly on the help for our users! For example, our users write blogs about their experience: https://michel-steuwer.github.io/About-CK . 

Maybe you can help the CK community and write how to add packages with makefiles? You can use this simple CK package as example:  https://github.com/ctuning/ck-env/tree/master/package/lib-openmpi-1.10.3-universal . We will be happy to help via Slack channel! I can also give you an access to our wiki pages on the CK GitHub if needed.

Also, feel free to discuss how to improve documentation via our CK mailing list– your help will be very appreciated by the CK community!

Once again, thanks a lot for your feedback and hope to keep in touch to improve CK documentation together in 2019!

**Comment by gfursin** [comment]
I opened a related ticket: https://github.com/ctuning/ck/issues/96

**Comment by gfursin** [comment]
I started working on a Sphinx-based documentation: https://github.com/ctuning/ck/tree/master/docs . It's available at https://cKnowledge.io/docs . I also updated the https://cKnowledge.org website. There is still a lot to be done (providing specs, commands, contributions), but we can open a new ticket for that ...
